"""
Django settings for aloestekhdam project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8&+faukjthx)0hysvx7__ct%8%02k$eyf3v0ew7^%!_d439e47'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My apps
    'corsheaders',
    'drf_yasg',
    'jobads',
    'blog',
    'rest_framework',
    'rest_framework.authtoken',
    'custom_users',
    'ckeditor',
    'user_dashboard',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ORIGIN_ALLOW_ALL = False

CSRF_TRUSTED_ORIGINS = ['https://*.45.144.126.224', "https://45.144.126.224", 'http://94.139.163.188',
                        'http://94.139.163.188:5000']

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5000',
    'https://aloestekhdam.com',
    'http://45.144.126.224:9000',
    'http://45.144.126.224',
    'http://94.139.163.188:5000',
    'http://94.139.163.188',
    'http://192.168.0.179:5000',
]

ALLOWED_HOSTS = ['*']

ROOT_URLCONF = 'aloestekhdam.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aloestekhdam.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'aloestekhdam',
        'USER': 'root',
        'PASSWORD': 'some_pass',
        'HOST': '185.112.150.109',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = 'static'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = "uploads/"

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ]
# }
#0.009
JWT_CONF = {
    'ACCESS_TOKEN_LIFETIME_HOURS': 2,
    'REFRESH_TOKEN_LIFETIME_DAYS': 5,
}

AUTH_USER_MODEL = 'custom_users.CustomUser'

CSRF_TRUSTED_ORIGINS = ['https://*.aloestekhdam.com', 'http://localhost:5000', 'http://45.144.126.224:9000']

STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'aloestekhdam.custom_s3.CustomS3Boto3Storage'
AWS_ACCESS_KEY_ID = 'pjpI0UzVpv3q8Wqi5o4r'
AWS_SECRET_ACCESS_KEY = 'N3N41QPIIpYVaJIH8JbsGCAJQ2GHzhDLBGSVVofy'
AWS_STORAGE_BUCKET_NAME = 'aloestekhdam'
STATIC_URL = f'https://storage.avalamozesh.com/{AWS_STORAGE_BUCKET_NAME}/static/'
AWS_S3_ENDPOINT_URL = 'https://storage.avalamozesh.com'
AWS_QUERYSTRING_AUTH = False
DEFAULT_IMAGE_URL = f'https://storage.avalamozesh.com/{AWS_STORAGE_BUCKET_NAME}/'
