# Generated by Django 4.2.5 on 2023-09-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='blog_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='blog.blog'),
            preserve_default=False,
        ),
    ]
