# Generated by Django 4.2.5 on 2023-10-04 09:50

import custom_users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('full_name', models.CharField(blank=True, max_length=250)),
                ('image', models.FileField(blank=True, upload_to=custom_users.models.image_upload_to)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('balance', models.CharField(blank=True, default=0, max_length=500)),
                ('user_cv', models.FileField(blank=True, upload_to=custom_users.models.cv_upload_to)),
                ('has_company', models.BooleanField(default=False)),
                ('industry', models.CharField(default='', max_length=250)),
                ('phone_number_2', models.CharField(default='', max_length=250)),
                ('website', models.CharField(blank=True, max_length=250)),
                ('company_telephone', models.CharField(default='', max_length=250)),
                ('company_telephone_2', models.CharField(default='', max_length=250)),
                ('organization_side', models.CharField(default='', max_length=250)),
                ('service_and_products', models.CharField(default='', max_length=250)),
                ('description_of_company', models.TextField(default='')),
                ('organization_size', models.CharField(default='', max_length=250)),
                ('company_name', models.CharField(default='', max_length=255)),
                ('type_of_activity', models.CharField(default='', max_length=250)),
                ('established_year', models.CharField(default='', max_length=250)),
                ('brand', models.CharField(default='', max_length=250)),
                ('ownership', models.CharField(default='', max_length=250)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('phone_number_verfiy', models.BooleanField(default=False)),
                ('user_type', models.CharField(default='casual', max_length=250)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('homepage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='custom_users.state'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
