# Generated by Django 4.2.5 on 2023-10-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
    ]
