# Generated by Django 4.2.5 on 2023-09-27 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('homepage', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.CharField(blank=True, default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='brand',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description_of_company',
            field=models.TextField(default='t'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='established_year',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(default='t', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_size',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ownership',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='t', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number_verfiy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service_and_products',
            field=models.CharField(default='t', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_of_activity',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.ManyToManyField(blank=True, to='custom_users.state'),
        ),
    ]
