# Generated by Django 4.2.5 on 2023-09-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_industrycategory_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organizationـsize',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
