# Generated by Django 4.2.5 on 2023-10-01 12:37

import custom_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_cv',
            field=models.FileField(blank=True, upload_to=custom_users.models.cv_upload_to),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description_of_company',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='service_and_products',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
