# Generated by Django 4.2.5 on 2023-09-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0004_rename_organizationـsize_customuser_organization_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number_verfiy',
            field=models.BooleanField(default=False),
        ),
    ]
