# Generated by Django 4.2.5 on 2023-10-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0005_alter_customuser_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
    ]
