# Generated by Django 4.2.5 on 2023-09-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0005_customuser_phone_number_verfiy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='industry',
        ),
        migrations.DeleteModel(
            name='IndustryCategory',
        ),
    ]
