# Generated by Django 4.2.5 on 2023-09-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0006_remove_customuser_industry_delete_industrycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.CharField(blank=True, default=0, max_length=500),
        ),
    ]
