# Generated by Django 4.2.5 on 2023-09-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0008_refreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='token',
        ),
    ]
