# Generated by Django 4.2.5 on 2023-09-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0010_customuser_brand_customuser_description_of_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('homepage', models.BooleanField(default=False)),
            ],
        ),
    ]
