# Generated by Django 4.2.5 on 2023-09-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0012_companycity_delete_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyCity',
            new_name='City',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.ManyToManyField(to='custom_users.city'),
        ),
    ]
