# Generated by Django 4.2.5 on 2023-09-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0014_alter_customuser_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ManyToManyField(blank=True, to='custom_users.city'),
        ),
    ]
