# Generated by Django 4.2.5 on 2023-09-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0015_alter_customuser_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='city',
            new_name='state',
        ),
    ]
