# Generated by Django 4.2.5 on 2023-10-04 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('work_time', models.CharField(max_length=250)),
                ('work_days', models.CharField(max_length=250)),
                ('income_range', models.CharField(max_length=250)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('telecommuting', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=100)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('hire_intern', models.BooleanField(default=False)),
                ('work_experience', models.CharField(max_length=100)),
                ('hire_military_service', models.BooleanField(default=False)),
                ('hire_disability', models.BooleanField(default=False)),
                ('education_group', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=500)),
                ('business_trip', models.CharField(max_length=100)),
                ('status', models.CharField(default='sent', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('homepage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobFacilitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='jobads.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(to='jobads.jobcategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='facilitie',
            field=models.ManyToManyField(to='jobads.jobfacilitie'),
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('status', models.CharField(default='sent', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jobad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='jobads.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_cv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
