# Generated by Django 4.2.5 on 2023-09-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='income_range',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='work_time',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
