# Generated by Django 4.2.5 on 2023-09-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0002_job_income_range_job_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='body',
        ),
    ]
