# Generated by Django 4.2.5 on 2023-09-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0006_city_alter_jobinfo_user_job_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='homepage',
            field=models.BooleanField(default=False),
        ),
    ]
