# Generated by Django 4.2.5 on 2023-09-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0007_city_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='t',blank=True, max_length=100),
            preserve_default=False,
        ),
    ]
