# Generated by Django 4.2.5 on 2023-10-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0007_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
