# Generated by Django 4.2.5 on 2023-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0009_alter_job_max_age_alter_job_min_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
