# Generated by Django 4.2.5 on 2023-09-11 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobads', '0009_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='business_trip',
            field=models.CharField(default='t', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cooperation',
            field=models.CharField(default='t', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='education_group',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='hire_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='hire_intern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='hire_military_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='max_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='min_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='telecommuting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='work_experience',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('job_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobads.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='jobads.jobskill'),
        ),
    ]
