# Generated by Django 4.2.5 on 2023-10-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0010_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='military_order',
            field=models.BooleanField(default=False),
        ),
    ]
