# Generated by Django 4.2.5 on 2023-09-11 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0010_job_business_trip_job_cooperation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFacilitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitie', models.CharField(max_length=100)),
                ('job_psot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobads.job')),
            ],
        ),
    ]
