# Generated by Django 4.2.5 on 2023-09-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0011_jobfacilitie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobfacilitie',
            old_name='job_psot',
            new_name='job_post',
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobads.job'),
        ),
    ]
