# Generated by Django 4.2.5 on 2023-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0012_jobcity_jobstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcity',
            name='char_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobstate',
            name='char_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
