# Generated by Django 4.2.5 on 2023-09-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0012_rename_job_psot_jobfacilitie_job_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=250)),
                ('job_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobads.job')),
            ],
        ),
    ]
