# Generated by Django 4.2.5 on 2023-09-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0013_jobindustry'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='facilitie',
            field=models.ManyToManyField(to='jobads.jobfacilitie'),
        ),
    ]
