# Generated by Django 4.2.5 on 2023-09-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0014_job_facilitie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfacilitie',
            name='job_post',
        ),
    ]
