# Generated by Django 4.2.5 on 2023-09-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0015_remove_jobfacilitie_job_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
    ]
