# Generated by Django 4.2.5 on 2023-10-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0016_remove_jobcity_related_state_jobstate_related_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstate',
            name='related_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_states', to='jobads.jobcity'),
        ),
    ]
