# Generated by Django 4.2.5 on 2023-09-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0017_job_work_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(default='t', max_length=250),
            preserve_default=False,
        ),
    ]
