# Generated by Django 4.2.5 on 2023-10-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0017_alter_jobstate_related_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstate',
            name='related_city',
        ),
        migrations.AddField(
            model_name='jobcity',
            name='related_states',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='jobads.jobcity'),
        ),
    ]
