# Generated by Django 4.2.5 on 2023-09-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0018_job_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobIndustry',
        ),
    ]
