# Generated by Django 4.2.5 on 2023-09-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0019_delete_jobindustry'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_travel',
            field=models.CharField(default='r', max_length=250),
            preserve_default=False,
        ),
    ]
