# Generated by Django 4.2.5 on 2023-09-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0020_job_work_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='work_travel',
        ),
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='t', max_length=250),
            preserve_default=False,
        ),
    ]
