# Generated by Django 4.2.5 on 2023-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0020_remove_jobcity_related_states_jobstate_related_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstate',
            name='related_city',
        ),
        migrations.AddField(
            model_name='jobstate',
            name='related_city',
            field=models.ManyToManyField(to='jobads.jobcity'),
        ),
    ]
