# Generated by Django 4.2.5 on 2023-10-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0021_remove_jobstate_related_city_jobstate_related_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstate',
            name='related_city',
        ),
        migrations.AddField(
            model_name='jobcity',
            name='related_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobads.jobstate'),
        ),
    ]
