# Generated by Django 4.2.5 on 2023-09-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0021_remove_job_work_travel_remove_job_city_delete_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cooperation',
        ),
    ]
