# Generated by Django 4.2.5 on 2023-09-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0022_remove_job_cooperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
