# Generated by Django 4.2.5 on 2023-10-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0023_cv_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
