# Generated by Django 4.2.5 on 2023-09-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0023_alter_job_slug_alter_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
