# Generated by Django 4.2.5 on 2023-10-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0025_remove_cv_viewed_alter_cv_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='status',
            field=models.CharField(default='sent', max_length=250),
        ),
    ]
