# Generated by Django 4.2.5 on 2023-09-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0025_delete_jobinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskill',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='jobads.job'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
