# Generated by Django 4.2.5 on 2023-09-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0026_alter_jobskill_job_post_alter_jobskill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='sent', max_length=255),
        ),
    ]
