# Generated by Django 4.2.5 on 2023-10-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0026_alter_cv_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='first_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='cv',
            name='job_slug',
            field=models.CharField(default='', max_length=250),
        ),
    ]
