# Generated by Django 4.2.5 on 2023-10-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0028_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='file_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cv',
            name='jobad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='jobads.job'),
        ),
    ]
