# Generated by Django 4.2.5 on 2023-10-02 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobads', '0029_alter_cv_file_name_alter_cv_jobad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_cv', to=settings.AUTH_USER_MODEL),
        ),
    ]
