# Generated by Django 4.2.5 on 2023-10-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0029_alter_job_rejected_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='business_trip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='education_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='facilitie',
            field=models.ManyToManyField(blank=True, to='jobads.jobfacilitie'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
