# Generated by Django 4.2.5 on 2023-10-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0030_alter_cv_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.TextField(max_length=250),
        ),
    ]
