# Generated by Django 4.2.4 on 2023-10-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0030_alter_job_business_trip_alter_job_education_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255, unique=True)),
                ('job_ad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobads.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.CharField(max_length=255, unique=True)),
                ('job_ad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobads.job')),
            ],
        ),
    ]
