# Generated by Django 4.2.5 on 2023-10-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0031_alter_job_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(max_length=250),
        ),
    ]
