# Generated by Django 4.2.4 on 2023-10-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0031_jobtime_jobincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobincome',
            name='job_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobads.job'),
        ),
        migrations.AlterField(
            model_name='jobtime',
            name='job_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobads.job'),
        ),
    ]
