# Generated by Django 4.2.5 on 2023-10-03 08:52

from django.db import migrations, models
import jobads.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0032_alter_job_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=''),
        ),
    ]
