# Generated by Django 4.2.5 on 2023-10-03 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0033_alter_job_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 8, 57, 52, 354438, tzinfo=datetime.timezone.utc)),
        ),
    ]
