# Generated by Django 4.2.5 on 2023-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0034_alter_job_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
