# Generated by Django 4.2.5 on 2023-10-03 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0035_alter_job_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
